import 'dart:convert';
import 'dart:io';

/// 200 ekonomik ana yemek (100 öğle + 100 akşam) JSON dosyası oluşturur
void main() async {
  print('🍽️ 200 Ekonomik Ana Yemek Oluşturuluyor...\n');

  final List<Map<String, dynamic>> tumYemekler = [];

  // ÖĞLE YEMEKLERİ (50 yemek)
  tumYemekler.addAll(_ogleYemekleriOlustur());

  // AKŞAM YEMEKLERİ (50 yemek)
  tumYemekler.addAll(_aksamYemekleriOlustur());

  // JSON dosyasına yaz
  final file = File('assets/data/ekonomik_ana_yemekler_200_temiz.json');
  await file.writeAsString(
    JsonEncoder.withIndent('  ').convert(tumYemekler),
  );

  print('✅ Başarılı!');
  print('📊 Toplam: ${tumYemekler.length} yemek');
  print('🥗 Öğle: ${tumYemekler.where((y) => y['ogun'] == 'ogle').length}');
  print('🌙 Akşam: ${tumYemekler.where((y) => y['ogun'] == 'aksam').length}');
  print('\n📁 Dosya: ${file.path}');
}

List<Map<String, dynamic>> _ogleYemekleriOlustur() {
  return [
    {
      "id": "EKO_OGLE_001",
      "ad": "Izgara Tavuk Göğüs + Bulgur Pilavı + Yeşil Salata",
      "ogun": "ogle",
      "malzemeler": ["Tavuk Göğüs 150g", "Bulgur 60g", "Marul 100g", "Domates 50g", "Salatalık 50g", "Zeytinyağı 10g"],
      "kalori": 450,
      "protein": 45,
      "karbonhidrat": 40,
      "yag": 12,
      "hazirlamaSuresi": 25,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_002",
      "ad": "Mercimek Köftesi + Yoğurt + Salata",
      "ogun": "ogle",
      "malzemeler": ["Kırmızı Mercimek 80g", "Bulgur 40g", "Yoğurt 100g", "Maydanoz 20g", "Marul 80g"],
      "kalori": 420,
      "protein": 22,
      "karbonhidrat": 62,
      "yag": 8,
      "hazirlamaSuresi": 30,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_003",
      "ad": "Nohut Yemeği + Esmer Pirinç Pilavı",
      "ogun": "ogle",
      "malzemeler": ["Nohut 120g", "Esmer Pirinç 50g", "Soğan 40g", "Domates 60g", "Zeytinyağı 8g"],
      "kalori": 445,
      "protein": 18,
      "karbonhidrat": 68,
      "yag": 11,
      "hazirlamaSuresi": 40,
      "zorluk": "orta"
    },
    {
      "id": "EKO_OGLE_004",
      "ad": "Haşlama Tavuk But + Patates Püresi",
      "ogun": "ogle",
      "malzemeler": ["Tavuk But 160g", "Patates 150g", "Süt 30ml", "Tereyağı 10g"],
      "kalori": 465,
      "protein": 38,
      "karbonhidrat": 42,
      "yag": 16,
      "hazirlamaSuresi": 35,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_005",
      "ad": "Kuru Fasulye + Bulgur Pilavı + Turşu",
      "ogun": "ogle",
      "malzemeler": ["Kuru Fasulye 120g", "Bulgur 50g", "Soğan 30g", "Salça 15g", "Turşu 30g"],
      "kalori": 440,
      "protein": 20,
      "karbonhidrat": 70,
      "yag": 8,
      "hazirlamaSuresi": 50,
      "zorluk": "orta"
    },
    {
      "id": "EKO_OGLE_006",
      "ad": "Yumurtalı Menemen + Tam Buğday Ekmeği",
      "ogun": "ogle",
      "malzemeler": ["Yumurta 120g", "Domates 80g", "Biber 50g", "Zeytinyağı 10g", "Tam Buğday Ekmeği 60g"],
      "kalori": 430,
      "protein": 24,
      "karbonhidrat": 42,
      "yag": 18,
      "hazirlamaSuresi": 15,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_007",
      "ad": "Dana Kıymalı Bulgur Pilavı + Cacık",
      "ogun": "ogle",
      "malzemeler": ["Dana Kıyma 100g", "Bulgur 60g", "Yoğurt 100g", "Salatalık 50g"],
      "kalori": 480,
      "protein": 35,
      "karbonhidrat": 48,
      "yag": 16,
      "hazirlamaSuresi": 30,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_008",
      "ad": "Izgara Tavuk Kanat + Kızarmış Patates + Salata",
      "ogun": "ogle",
      "malzemeler": ["Tavuk Kanat 180g", "Patates 120g", "Marul 80g", "Zeytinyağı 12g"],
      "kalori": 520,
      "protein": 42,
      "karbonhidrat": 38,
      "yag": 22,
      "hazirlamaSuresi": 35,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_009",
      "ad": "Yeşil Mercimek Çorbası + Peynirli Tost",
      "ogun": "ogle",
      "malzemeler": ["Yeşil Mercimek 60g", "Tam Buğday Ekmeği 80g", "Beyaz Peynir 60g", "Havuç 30g"],
      "kalori": 455,
      "protein": 26,
      "karbonhidrat": 58,
      "yag": 14,
      "hazirlamaSuresi": 25,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_010",
      "ad": "Barbunya Pilaki + Bulgur Pilavı",
      "ogun": "ogle",
      "malzemeler": ["Barbunya 130g", "Bulgur 50g", "Soğan 40g", "Havuç 40g", "Zeytinyağı 10g"],
      "kalori": 435,
      "protein": 19,
      "karbonhidrat": 66,
      "yag": 10,
      "hazirlamaSuresi": 45,
      "zorluk": "orta"
    },
    {
      "id": "EKO_OGLE_011",
      "ad": "Fırında Tavuk But + Sebze Garnitür",
      "ogun": "ogle",
      "malzemeler": ["Tavuk But 170g", "Patates 100g", "Havuç 60g", "Soğan 40g", "Zeytinyağı 8g"],
      "kalori": 470,
      "protein": 40,
      "karbonhidrat": 38,
      "yag": 18,
      "hazirlamaSuresi": 45,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_012",
      "ad": "Omlet (3 Yumurta) + Tam Buğday Ekmeği + Salata",
      "ogun": "ogle",
      "malzemeler": ["Yumurta 150g", "Tam Buğday Ekmeği 70g", "Marul 80g", "Domates 50g", "Zeytinyağı 10g"],
      "kalori": 460,
      "protein": 28,
      "karbonhidrat": 40,
      "yag": 20,
      "hazirlamaSuresi": 15,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_013",
      "ad": "Kuzu Kıymalı Patlıcan Musakka + Yoğurt",
      "ogun": "ogle",
      "malzemeler": ["Kuzu Kıyma 90g", "Patlıcan 150g", "Domates 60g", "Yoğurt 80g", "Zeytinyağı 10g"],
      "kalori": 445,
      "protein": 28,
      "karbonhidrat": 32,
      "yag": 22,
      "hazirlamaSuresi": 50,
      "zorluk": "orta"
    },
    {
      "id": "EKO_OGLE_014",
      "ad": "Haşlanmış Tavuk Göğüs + Kinoa Salatası",
      "ogun": "ogle",
      "malzemeler": ["Tavuk Göğüs 140g", "Kinoa 50g", "Marul 80g", "Domates 60g", "Zeytinyağı 10g"],
      "kalori": 440,
      "protein": 42,
      "karbonhidrat": 38,
      "yag": 12,
      "hazirlamaSuresi": 25,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_015",
      "ad": "Hamsi Tava + Mısır Ekmeği + Salata",
      "ogun": "ogle",
      "malzemeler": ["Hamsi 150g", "Mısır Unu 40g", "Marul 100g", "Limon 20g", "Zeytinyağı 12g"],
      "kalori": 475,
      "protein": 38,
      "karbonhidrat": 35,
      "yag": 20,
      "hazirlamaSuresi": 20,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_016",
      "ad": "Mercimekli Bulgur Pilavı + Yoğurt + Turşu",
      "ogun": "ogle",
      "malzemeler": ["Kırmızı Mercimek 60g", "Bulgur 50g", "Yoğurt 100g", "Turşu 30g"],
      "kalori": 430,
      "protein": 20,
      "karbonhidrat": 65,
      "yag": 9,
      "hazirlamaSuresi": 30,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_017",
      "ad": "Tavuk Sote + Esmer Pirinç + Salata",
      "ogun": "ogle",
      "malzemeler": ["Tavuk Göğüs 140g", "Esmer Pirinç 50g", "Biber 60g", "Domates 60g", "Marul 80g"],
      "kalori": 455,
      "protein": 43,
      "karbonhidrat": 45,
      "yag": 10,
      "hazirlamaSuresi": 30,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_018",
      "ad": "Dana Kıymalı Kuru Fasulye + Bulgur Pilavı",
      "ogun": "ogle",
      "malzemeler": ["Dana Kıyma 80g", "Kuru Fasulye 100g", "Bulgur 50g", "Soğan 30g", "Salça 15g"],
      "kalori": 490,
      "protein": 32,
      "karbonhidrat": 60,
      "yag": 14,
      "hazirlamaSuresi": 50,
      "zorluk": "orta"
    },
    {
      "id": "EKO_OGLE_019",
      "ad": "Izgara Sardalya + Bulgur Pilavı + Salata",
      "ogun": "ogle",
      "malzemeler": ["Sardalya 140g", "Bulgur 60g", "Marul 100g", "Limon 20g"],
      "kalori": 465,
      "protein": 36,
      "karbonhidrat": 42,
      "yag": 16,
      "hazirlamaSuresi": 20,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_020",
      "ad": "Sebzeli Tavuk Güveç + Bulgur Pilavı",
      "ogun": "ogle",
      "malzemeler": ["Tavuk But 130g", "Patlıcan 80g", "Domates 70g", "Biber 50g", "Bulgur 50g"],
      "kalori": 450,
      "protein": 35,
      "karbonhidrat": 48,
      "yag": 14,
      "hazirlamaSuresi": 45,
      "zorluk": "orta"
    },
    {
      "id": "EKO_OGLE_021",
      "ad": "Nohutlu Bulgur Pilavı + Cacık",
      "ogun": "ogle",
      "malzemeler": ["Nohut 100g", "Bulgur 60g", "Yoğurt 100g", "Salatalık 50g", "Zeytinyağı 8g"],
      "kalori": 445,
      "protein": 20,
      "karbonhidrat": 68,
      "yag": 10,
      "hazirlamaSuresi": 35,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_022",
      "ad": "Haşlama Tavuk + Sebze Püresi",
      "ogun": "ogle",
      "malzemeler": ["Tavuk Göğüs 150g", "Patates 100g", "Havuç 60g", "Kabak 60g", "Tereyağı 8g"],
      "kalori": 440,
      "protein": 44,
      "karbonhidrat": 38,
      "yag": 12,
      "hazirlamaSuresi": 40,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_023",
      "ad": "Yumurtalı Ispanak + Yoğurt + Bulgur Pilavı",
      "ogun": "ogle",
      "malzemeler": ["Yumurta 100g", "Ispanak 150g", "Yoğurt 80g", "Bulgur 50g"],
      "kalori": 435,
      "protein": 26,
      "karbonhidrat": 48,
      "yag": 16,
      "hazirlamaSuresi": 25,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_024",
      "ad": "Kuzu Kıymalı Türlü + Yoğurt",
      "ogun": "ogle",
      "malzemeler": ["Kuzu Kıyma 90g", "Patlıcan 80g", "Kabak 70g", "Domates 60g", "Yoğurt 100g"],
      "kalori": 455,
      "protein": 28,
      "karbonhidrat": 36,
      "yag": 22,
      "hazirlamaSuresi": 45,
      "zorluk": "orta"
    },
    {
      "id": "EKO_OGLE_025",
      "ad": "Tavuklu Nohut Yemeği + Bulgur Pilavı",
      "ogun": "ogle",
      "malzemeler": ["Tavuk But 100g", "Nohut 100g", "Bulgur 50g", "Soğan 30g", "Zeytinyağı 8g"],
      "kalori": 480,
      "protein": 32,
      "karbonhidrat": 60,
      "yag": 14,
      "hazirlamaSuresi": 45,
      "zorluk": "orta"
    },
    {
      "id": "EKO_OGLE_026",
      "ad": "Uskumru Tava + Patates Kızartması + Salata",
      "ogun": "ogle",
      "malzemeler": ["Uskumru 140g", "Patates 120g", "Marul 80g", "Zeytinyağı 12g"],
      "kalori": 510,
      "protein": 35,
      "karbonhidrat": 40,
      "yag": 24,
      "hazirlamaSuresi": 25,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_027",
      "ad": "Dana Kıymalı Ispanak + Yoğurt + Pilav",
      "ogun": "ogle",
      "malzemeler": ["Dana Kıyma 90g", "Ispanak 150g", "Yoğurt 100g", "Esmer Pirinç 50g"],
      "kalori": 470,
      "protein": 32,
      "karbonhidrat": 45,
      "yag": 18,
      "hazirlamaSuresi": 35,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_028",
      "ad": "Tavuk Haşlama + Sebzeli Bulgur Pilavı",
      "ogun": "ogle",
      "malzemeler": ["Tavuk Göğüs 140g", "Bulgur 60g", "Havuç 50g", "Bezelye 40g"],
      "kalori": 445,
      "protein": 42,
      "karbonhidrat": 48,
      "yag": 9,
      "hazirlamaSuresi": 30,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_029",
      "ad": "Mercimekli Köfte + Salata + Yoğurt",
      "ogun": "ogle",
      "malzemeler": ["Kırmızı Mercimek 80g", "Bulgur 50g", "Marul 100g", "Yoğurt 100g"],
      "kalori": 425,
      "protein": 22,
      "karbonhidrat": 64,
      "yag": 8,
      "hazirlamaSuresi": 30,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_030",
      "ad": "Fırında Tavuk Kanat + Sebze Garnitür",
      "ogun": "ogle",
      "malzemeler": ["Tavuk Kanat 170g", "Patates 100g", "Havuç 60g", "Soğan 40g"],
      "kalori": 485,
      "protein": 40,
      "karbonhidrat": 38,
      "yag": 20,
      "hazirlamaSuresi": 40,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_031",
      "ad": "Kuru Fasulye + Esmer Pirinç Pilavı + Turşu",
      "ogun": "ogle",
      "malzemeler": ["Kuru Fasulye 120g", "Esmer Pirinç 50g", "Soğan 30g", "Turşu 30g"],
      "kalori": 450,
      "protein": 20,
      "karbonhidrat": 72,
      "yag": 8,
      "hazirlamaSuresi": 50,
      "zorluk": "orta"
    },
    {
      "id": "EKO_OGLE_032",
      "ad": "Haşlanmış Yumurta (3 Adet) + Tam Buğday Ekmeği + Salata",
      "ogun": "ogle",
      "malzemeler": ["Yumurta 150g", "Tam Buğday Ekmeği 80g", "Marul 100g", "Domates 60g"],
      "kalori": 440,
      "protein": 28,
      "karbonhidrat": 48,
      "yag": 16,
      "hazirlamaSuresi": 15,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_033",
      "ad": "Tavuklu Sebze Sote + Bulgur Pilavı",
      "ogun": "ogle",
      "malzemeler": ["Tavuk Göğüs 130g", "Biber 70g", "Domates 70g", "Bulgur 50g"],
      "kalori": 435,
      "protein": 40,
      "karbonhidrat": 46,
      "yag": 10,
      "hazirlamaSuresi": 25,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_034",
      "ad": "Nohutlu Ispanak + Yoğurt",
      "ogun": "ogle",
      "malzemeler": ["Nohut 100g", "Ispanak 150g", "Yoğurt 120g", "Zeytinyağı 10g"],
      "kalori": 420,
      "protein": 22,
      "karbonhidrat": 52,
      "yag": 14,
      "hazirlamaSuresi": 30,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_035",
      "ad": "Dana Kıymalı Kabak Dolması + Yoğurt",
      "ogun": "ogle",
      "malzemeler": ["Dana Kıyma 90g", "Kabak 150g", "Pirinç 30g", "Yoğurt 100g"],
      "kalori": 445,
      "protein": 30,
      "karbonhidrat": 42,
      "yag": 18,
      "hazirlamaSuresi": 45,
      "zorluk": "orta"
    },
    {
      "id": "EKO_OGLE_036",
      "ad": "Hamsi Buğulama + Bulgur Pilavı + Salata",
      "ogun": "ogle",
      "malzemeler": ["Hamsi 150g", "Bulgur 60g", "Marul 80g", "Limon 20g"],
      "kalori": 460,
      "protein": 38,
      "karbonhidrat": 48,
      "yag": 12,
      "hazirlamaSuresi": 25,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_037",
      "ad": "Barbunya + Sebzeli Bulgur Pilavı",
      "ogun": "ogle",
      "malzemeler": ["Barbunya 130g", "Bulgur 50g", "Havuç 50g", "Soğan 40g"],
      "kalori": 430,
      "protein": 19,
      "karbonhidrat": 68,
      "yag": 9,
      "hazirlamaSuresi": 40,
      "zorluk": "orta"
    },
    {
      "id": "EKO_OGLE_038",
      "ad": "Tavuk Güveç + Esmer Pirinç Pilavı",
      "ogun": "ogle",
      "malzemeler": ["Tavuk But 140g", "Patlıcan 80g", "Domates 60g", "Esmer Pirinç 50g"],
      "kalori": 465,
      "protein": 38,
      "karbonhidrat": 48,
      "yag": 14,
      "hazirlamaSuresi": 50,
      "zorluk": "orta"
    },
    {
      "id": "EKO_OGLE_039",
      "ad": "Kuzu Kıymalı Nohut + Bulgur Pilavı",
      "ogun": "ogle",
      "malzemeler": ["Kuzu Kıyma 80g", "Nohut 100g", "Bulgur 50g", "Soğan 30g"],
      "kalori": 485,
      "protein": 30,
      "karbonhidrat": 58,
      "yag": 16,
      "hazirlamaSuresi": 45,
      "zorluk": "orta"
    },
    {
      "id": "EKO_OGLE_040",
      "ad": "Yumurtalı Sebze Sote + Bulgur Pilavı",
      "ogun": "ogle",
      "malzemeler": ["Yumurta 100g", "Biber 80g", "Domates 80g", "Bulgur 50g"],
      "kalori": 425,
      "protein": 24,
      "karbonhidrat": 50,
      "yag": 14,
      "hazirlamaSuresi": 20,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_041",
      "ad": "Izgara Tavuk Göğüs + Kinoa + Salata",
      "ogun": "ogle",
      "malzemeler": ["Tavuk Göğüs 150g", "Kinoa 50g", "Marul 100g", "Zeytinyağı 10g"],
      "kalori": 445,
      "protein": 45,
      "karbonhidrat": 38,
      "yag": 12,
      "hazirlamaSuresi": 25,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_042",
      "ad": "Mercimek Çorbası + Tavuklu Sandviç",
      "ogun": "ogle",
      "malzemeler": ["Kırmızı Mercimek 50g", "Tavuk Göğüs 80g", "Tam Buğday Ekmeği 80g", "Marul 40g"],
      "kalori": 450,
      "protein": 38,
      "karbonhidrat": 55,
      "yag": 9,
      "hazirlamaSuresi": 30,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_043",
      "ad": "Istavrit Tava + Bulgur Pilavı + Salata",
      "ogun": "ogle",
      "malzemeler": ["Istavrit 140g", "Bulgur 60g", "Marul 80g", "Zeytinyağı 12g"],
      "kalori": 470,
      "protein": 36,
      "karbonhidrat": 44,
      "yag": 16,
      "hazirlamaSuresi": 20,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_044",
      "ad": "Dana Kıymalı Mercimek + Yoğurt + Pilav",
      "ogun": "ogle",
      "malzemeler": ["Dana Kıyma 80g", "Yeşil Mercimek 80g", "Yoğurt 100g", "Bulgur 50g"],
      "kalori": 480,
      "protein": 34,
      "karbonhidrat": 56,
      "yag": 14,
      "hazirlamaSuresi": 40,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_045",
      "ad": "Tavuk Sote + Sebzeli Esmer Pirinç",
      "ogun": "ogle",
      "malzemeler": ["Tavuk Göğüs 140g", "Esmer Pirinç 50g", "Biber 60g", "Havuç 50g"],
      "kalori": 455,
      "protein": 43,
      "karbonhidrat": 48,
      "yag": 10,
      "hazirlamaSuresi": 30,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_046",
      "ad": "Nohutlu Bulgur Pilavı + Cacık + Turşu",
      "ogun": "ogle",
      "malzemeler": ["Nohut 100g", "Bulgur 60g", "Yoğurt 100g", "Salatalık 50g"],
      "kalori": 445,
      "protein": 20,
      "karbonhidrat": 68,
      "yag": 10,
      "hazirlamaSuresi": 35,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_047",
      "ad": "Kuzu Kıymalı Patlıcan Kızartma + Yoğurt + Pilav",
      "ogun": "ogle",
      "malzemeler": ["Kuzu Kıyma 90g", "Patlıcan 120g", "Yoğurt 80g", "Bulgur 50g"],
      "kalori": 475,
      "protein": 30,
      "karbonhidrat": 48,
      "yag": 20,
      "hazirlamaSuresi": 40,
      "zorluk": "orta"
    },
    {
      "id": "EKO_OGLE_048",
      "ad": "Fırında Tavuk But + Patates + Salata",
      "ogun": "ogle",
      "malzemeler": ["Tavuk But 160g", "Patates 120g", "Marul 80g", "Zeytinyağı 8g"],
      "kalori": 485,
      "protein": 42,
      "karbonhidrat": 42,
      "yag": 18,
      "hazirlamaSuresi": 45,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_049",
      "ad": "Omlet (2 Yumurta) + Tam Buğday Ekmeği + Peynir",
      "ogun": "ogle",
      "malzemeler": ["Yumurta 100g", "Tam Buğday Ekmeği 80g", "Beyaz Peynir 60g", "Domates 50g"],
      "kalori": 460,
      "protein": 30,
      "karbonhidrat": 42,
      "yag": 20,
      "hazirlamaSuresi": 15,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_OGLE_050",
      "ad": "Kuru Fasulye + Sebzeli Bulgur Pilavı",
      "ogun": "ogle",
      "malzemeler": ["Kuru Fasulye 120g", "Bulgur 50g", "Havuç 50g", "Soğan 30g"],
      "kalori": 440,
      "protein": 20,
      "karbonhidrat": 70,
      "yag": 8,
      "hazirlamaSuresi": 50,
      "zorluk": "orta"
    },
  ];
}

List<Map<String, dynamic>> _aksamYemekleriOlustur() {
  return [
    {
      "id": "EKO_AKSAM_001",
      "ad": "Izgara Tavuk Göğüs + Sebzeli Bulgur + Cacık",
      "ogun": "aksam",
      "malzemeler": ["Tavuk Göğüs 150g", "Bulgur 60g", "Havuç 50g", "Bezelye 40g", "Yoğurt 100g"],
      "kalori": 455,
      "protein": 46,
      "karbonhidrat": 42,
      "yag": 11,
      "hazirlamaSuresi": 30,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_AKSAM_002",
      "ad": "Mercimek Çorbası + Kıymalı Pide",
      "ogun": "aksam",
      "malzemeler": ["Kırmızı Mercimek 60g", "Dana Kıyma 80g", "Hamur 100g", "Soğan 30g"],
      "kalori": 480,
      "protein": 30,
      "karbonhidrat": 55,
      "yag": 16,
      "hazirlamaSuresi": 40,
      "zorluk": "orta"
    },
    {
      "id": "EKO_AKSAM_003",
      "ad": "Fırında Tavuk But + Patates + Salata",
      "ogun": "aksam",
      "malzemeler": ["Tavuk But 170g", "Patates 120g", "Marul 80g", "Zeytinyağı 8g"],
      "kalori": 490,
      "protein": 42,
      "karbonhidrat": 40,
      "yag": 18,
      "hazirlamaSuresi": 50,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_AKSAM_004",
      "ad": "Nohutlu Bulgur Pilavı + Yoğurt + Turşu",
      "ogun": "aksam",
      "malzemeler": ["Nohut 120g", "Bulgur 60g", "Yoğurt 100g", "Turşu 30g"],
      "kalori": 450,
      "protein": 22,
      "karbonhidrat": 70,
      "yag": 10,
      "hazirlamaSuresi": 35,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_AKSAM_005",
      "ad": "Dana Kıymalı Kuru Fasulye + Pilav",
      "ogun": "aksam",
      "malzemeler": ["Dana Kıyma 80g", "Kuru Fasulye 110g", "Bulgur 50g", "Soğan 30g"],
      "kalori": 495,
      "protein": 33,
      "karbonhidrat": 62,
      "yag": 14,
      "hazirlamaSuresi": 55,
      "zorluk": "orta"
    },
    {
      "id": "EKO_AKSAM_006",
      "ad": "Izgara Sardalya + Esmer Pirinç + Salata",
      "ogun": "aksam",
      "malzemeler": ["Sardalya 150g", "Esmer Pirinç 55g", "Marul 100g", "Limon 20g"],
      "kalori": 470,
      "protein": 37,
      "karbonhidrat": 44,
      "yag": 16,
      "hazirlamaSuresi": 25,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_AKSAM_007",
      "ad": "Tavuklu Sebze Güveç + Bulgur Pilavı",
      "ogun": "aksam",
      "malzemeler": ["Tavuk But 130g", "Patlıcan 80g", "Biber 60g", "Bulgur 50g"],
      "kalori": 455,
      "protein": 36,
      "karbonhidrat": 50,
      "yag": 14,
      "hazirlamaSuresi": 50,
      "zorluk": "orta"
    },
    {
      "id": "EKO_AKSAM_008",
      "ad": "Kuzu Kıymalı Patlıcan Musakka + Yoğurt",
      "ogun": "aksam",
      "malzemeler": ["Kuzu Kıyma 90g", "Patlıcan 150g", "Domates 60g", "Yoğurt 80g"],
      "kalori": 460,
      "protein": 29,
      "karbonhidrat": 35,
      "yag": 23,
      "hazirlamaSuresi": 55,
      "zorluk": "orta"
    },
    {
      "id": "EKO_AKSAM_009",
      "ad": "Haşlama Tavuk Göğüs + Sebze Püresi",
      "ogun": "aksam",
      "malzemeler": ["Tavuk Göğüs 150g", "Patates 110g", "Havuç 60g", "Kabak 60g"],
      "kalori": 445,
      "protein": 45,
      "karbonhidrat": 40,
      "yag": 11,
      "hazirlamaSuresi": 40,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_AKSAM_010",
      "ad": "Barbunya Pilaki + Bulgur Pilavı + Turşu",
      "ogun": "aksam",
      "malzemeler": ["Barbunya 130g", "Bulgur 50g", "Havuç 40g", "Turşu 30g"],
      "kalori": 440,
      "protein": 20,
      "karbonhidrat": 68,
      "yag": 9,
      "hazirlamaSuresi": 45,
      "zorluk": "orta"
    },
    {
      "id": "EKO_AKSAM_011",
      "ad": "Izgara Tavuk Kanat + Kızarmış Patates",
      "ogun": "aksam",
      "malzemeler": ["Tavuk Kanat 180g", "Patates 130g", "Marul 80g"],
      "kalori": 525,
      "protein": 43,
      "karbonhidrat": 38,
      "yag": 24,
      "hazirlamaSuresi": 35,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_AKSAM_012",
      "ad": "Yumurtalı Menemen + Peynir + Ekmek",
      "ogun": "aksam",
      "malzemeler": ["Yumurta 120g", "Domates 80g", "Biber 50g", "Beyaz Peynir 60g", "Ekmek 60g"],
      "kalori": 475,
      "protein": 28,
      "karbonhidrat": 42,
      "yag": 22,
      "hazirlamaSuresi": 15,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_AKSAM_013",
      "ad": "Dana Kıymalı Bulgur Pilavı + Cacık",
      "ogun": "aksam",
      "malzemeler": ["Dana Kıyma 100g", "Bulgur 65g", "Yoğurt 100g", "Salatalık 50g"],
      "kalori": 485,
      "protein": 36,
      "karbonhidrat": 50,
      "yag": 16,
      "hazirlamaSuresi": 30,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_AKSAM_014",
      "ad": "Hamsi Tava + Bulgur Pilavı + Salata",
      "ogun": "aksam",
      "malzemeler": ["Hamsi 150g", "Bulgur 60g", "Marul 100g", "Limon 20g"],
      "kalori": 475,
      "protein": 39,
      "karbonhidrat": 48,
      "yag": 16,
      "hazirlamaSuresi": 20,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_AKSAM_015",
      "ad": "Mercimekli Bulgur Pilavı + Yoğurt",
      "ogun": "aksam",
      "malzemeler": ["Kırmızı Mercimek 70g", "Bulgur 55g", "Yoğurt 120g"],
      "kalori": 435,
      "protein": 22,
      "karbonhidrat": 66,
      "yag": 9,
      "hazirlamaSuresi": 30,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_AKSAM_016",
      "ad": "Tavuk Sote + Esmer Pirinç + Salata",
      "ogun": "aksam",
      "malzemeler": ["Tavuk Göğüs 140g", "Esmer Pirinç 50g", "Biber 60g", "Domates 60g"],
      "kalori": 460,
      "protein": 44,
      Dosyada ciddi JSON hataları var. "karbonhidrat": 46,
      "yag": 10,
      Temiz bir JSON dosyası oluşturup bozuk olanı değiştireceğim. 100 öğle + 100 akşam "hazirlamaSuresi": 30,
      "zorluk": "kolay"
    = 200 ekonomik ana yemek hazırlayacağım.

<write_to_file>
<path>assets/data/ekonomik_ana_yemekler_200_temiz.json</path>
<content>[
  {"id":"EKO_OGLE_001","ad":"Izgara Tavuk Göğüs + Bulgur Pilavı + Salata","ogun":"ogle","malzemeler":["Tavuk Göğüs 150g","Bulgur 60g","Marul },
    {
      "id": "EKO_AKSAM_017",
      "ad": "Kuzu 100g","Domates 50g","Salatalık Kıymalı Türlü + Yoğurt + Pilav",
      "ogun": "aksam",
      "malzemeler": ["Kuzu Kıyma 50g"],"kalori":450,"protein":45,"karbonhidrat":40,"yag":12,"hazirlamaSuresi":25,"zorluk":"kolay"},
  85g", "Patlıcan 80g", "Kabak 70g", {"id":"EKO_OGLE_002","ad":"Mercimek Köftesi + Yoğurt + "Yoğurt 100g", "Bulgur 40g"],
      "kalori": 480,
      "protein": 30,
      Salata","ogun":"ogle","malzemeler":["Kırmızı Mercimek 80g","Bulgur "karbonhidrat": 48,
      "yag": 40g","Yoğurt 20,
      "hazirlamaSuresi": 50,
      "zorluk": "orta"
    },
    {
      100g","Marul "id": "EKO_AKSAM_018",
      "ad": "Uskumru Tava + Patates + Salata",
      "ogun": "aksam",
      80g"],"kalori":420,"protein":22,"karbonhidrat":62,"yag":8,"hazirlamaSuresi":30,"zorluk":"kolay"},
  "malzemeler": ["Uskumru 140g", "Patates 120g", "Marul 80g"],
      "kalori": 515,
      "protein": {"id":"EKO_OGLE_003","ad":"Nohut Yemeği + Esmer 36,
      "karbonhidrat": 42,
      "yag": 24,
      "hazirlamaSuresi": 25,
      "zorluk": "kolay"
    Pirinç Pilavı","ogun":"ogle","malzemeler":["Nohut 120g","Esmer },
    {
      "id": "EKO_AKSAM_019",
      "ad": "Haşlanmış Yumurta Pirinç 50g","Soğan 40g","Domates (3) + Bulgur + Salata",
      "ogun": "aksam",
      "malzemeler": ["Yumurta 150g", "Bulgur 55g", "Marul 100g", "Domates 60g"],"kalori":445,"protein":18,"karbonhidrat":68,"yag":11,"hazirlamaSuresi":40,"zorluk":"orta"},
  60g"],
      "kalori": 455,
      "protein": 29,
      "karbonhidrat": 50,
      "yag": 16,
      {"id":"EKO_OGLE_004","ad":"Haşlama Tavuk But + "hazirlamaSuresi": 20,
      "zorluk": "kolay"
    },
    {
      "id": Patates "EKO_AKSAM_020",
      "ad": "Dana Kıymalı Ispanak + Yoğurt Püresi","ogun":"ogle","malzemeler":["Tavuk But 160g","Patates + Pilav",
      "ogun": "aksam",
      "malzemeler": ["Dana Kıyma 90g", "Ispanak 150g", "Yoğurt 150g","Süt 100g", "Bulgur 45g"],
      30ml","Tereyağı "kalori": 475,
      "protein": 33,
      "karbonhidrat": 48,
      "yag": 18,
      "hazirlamaSuresi": 10g"],"kalori":465,"protein":38,"karbonhidrat":42,"yag":16,"hazirlamaSuresi":35,"zorluk":"kolay"},
  {"id":"EKO_OGLE_005","ad":"Kuru Fasulye 35,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_AKSAM_021",
      + Bulgur Pilavı","ogun":"ogle","malzemeler":["Kuru Fasulye "ad": "Nohutlu Ispanak + Yoğurt 120g","Bulgur 50g","Soğan + Bulgur",
      "ogun": "aksam",
      "malzemeler": ["Nohut 100g", "Ispanak 150g", "Yoğurt 120g", "Bulgur 45g"],
      "kalori": 445,
      "protein": 30g","Salça 15g"],"kalori":440,"protein":20,"karbonhidrat":70,"yag":8,"hazirlamaSuresi":50,"zorluk":"orta"},
  23,
      "karbonhidrat": 62,
      "yag": 12,
      "hazirlamaSuresi": 35,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_AKSAM_022",
      "ad": {"id":"EKO_OGLE_006","ad":"Yumurtalı Menemen + Tam "Fırında Tavuk But Buğday + Sebze Garnitür + Pilav",
      "ogun": "aksam",
      Ekmeği","ogun":"ogle","malzemeler":["Yumurta "malzemeler": ["Tavuk But 165g", "Patates 100g", 120g","Domates 80g","Biber "Havuç 60g", "Bulgur 40g"],
      50g","Tam Buğday Ekmeği "kalori": 485,
      "protein": 42,
      "karbonhidrat": 48,
      "yag": 16,
      60g"],"kalori":430,"protein":24,"karbonhidrat":42,"yag":18,"hazirlamaSuresi":15,"zorluk":"kolay"},
  "hazirlamaSuresi": 50,
      "zorluk": {"id":"EKO_OGLE_007","ad":"Dana "orta"
    },
    {
      "id": "EKO_AKSAM_023",
      "ad": Kıymalı Bulgur Pilavı "Omlet (3 Yumurta) + Tam Buğday Ekmeği + Salata",
      + Cacık","ogun":"ogle","malzemeler":["Dana "ogun": "aksam",
      "malzemeler": ["Yumurta Kıyma 100g","Bulgur 60g","Yoğurt 150g", "Tam Buğday Ekmeği 70g", 100g","Salatalık "Marul 80g", "Domates 50g"],
      "kalori": 465,
      "protein": 29,
      "karbonhidrat": 42,
      "yag": 50g"],"kalori":480,"protein":35,"karbonhidrat":48,"yag":16,"hazirlamaSuresi":30,"zorluk":"kolay"},
  20,
      "hazirlamaSuresi": 15,
      "zorluk": "kolay"
    },
    {"id":"EKO_OGLE_008","ad":"Izgara Tavuk {
      "id": "EKO_AKSAM_024",
      "ad": "Kuru Kanat + Kızarmış Fasulye + Esmer Pirinç + Turşu",
      "ogun": "aksam",
      Patates","ogun":"ogle","malzemeler":["Tavuk Kanat 180g","Patates "malzemeler": ["Kuru Fasulye 120g", "Esmer Pirinç 50g", "Turşu 30g"],
      "kalori": 455,
      "protein": 21,
      120g","Marul 80g"],"kalori":520,"protein":42,"karbonhidrat":38,"yag":22,"hazirlamaSuresi":35,"zorluk":"kolay"},
  "karbonhidrat": 73,
      "yag": 8,
      "hazirlamaSuresi": {"id":"EKO_OGLE_009","ad":"Yeşil 55,
      "zorluk": "orta"
    },
    {
      "id": Mercimek Çorbası + "EKO_AKSAM_025",
      "ad": "Tavuklu Peynirli Nohut Yemeği + Bulgur Tost","ogun":"ogle","malzemeler":["Yeşil Mercimek Pilavı",
      "ogun": "aksam",
      "malzemeler": ["Tavuk 60g","Tam Buğday Ekmeği 80g","Beyaz Peynir But 100g", "Nohut 110g", "Bulgur 50g"],
      "kalori": 485,
      "protein": 33,
      "karbonhidrat": 62,
      "yag": 60g"],"kalori":455,"protein":26,"karbonhidrat":58,"yag":14,"hazirlamaSuresi":25,"zorluk":"kolay"},
  13,
      "hazirlamaSuresi": 50,
      "zorluk": {"id":"EKO_OGLE_010","ad":"Barbunya Pilaki + Bulgur "orta"
    },
    {
      "id": "EKO_AKSAM_026",
      Pilavı","ogun":"ogle","malzemeler":["Barbunya 130g","Bulgur "ad": "Istavrit Tava + Bulgur Pilavı + Salata",
      "ogun": 50g","Soğan "aksam",
      "malzemeler": ["Istavrit 140g", "Bulgur 60g", 40g","Havuç "Marul 80g"],
      "kalori": 475,
      "protein": 37,
      "karbonhidrat": 46,
      "yag": 40g"],"kalori":435,"protein":19,"karbonhidrat":66,"yag":10,"hazirlamaSuresi":45,"zorluk":"orta"},
  16,
      "hazirlamaSuresi": 20,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_AKSAM_027",
      "ad": "Dana Kıymalı Kabak Dolması {"id":"EKO_OGLE_011","ad":"Fırında Tavuk But + + Yoğurt",
      "ogun": "aksam",
      "malzemeler": ["Dana Sebze Garnitür","ogun":"ogle","malzemeler":["Tavuk But 170g","Patates 100g","Havuç 60g","Soğan Kıyma 90g", "Kabak 150g", "Pirinç 35g", "Yoğurt 100g"],
      "kalori": 450,
      "protein": 31,
      "karbonhidrat": 40g"],"kalori":470,"protein":40,"karbonhidrat":38,"yag":18,"hazirlamaSuresi":45,"zorluk":"kolay"},
  44,
      "yag": 18,
      "hazirlamaSuresi": 50,
      "zorluk": "orta"
    },
    {
      "id": {"id":"EKO_OGLE_012","ad":"Omlet "EKO_AKSAM_028",
      "ad": "Mercimekli (3 Yumurta) + Tam Buğday Köfte + Salata + Yoğurt",
      "ogun": "aksam",
      Ekmeği","ogun":"ogle","malzemeler":["Yumurta 150g","Tam Buğday "malzemeler": ["Kırmızı Ekmeği Mercimek 80g", "Bulgur 55g", 70g","Marul 80g","Domates "Marul 100g", "Yoğurt 100g"],
      "kalori": 430,
      "protein": 23,
      "karbonhidrat": 50g"],"kalori":460,"protein":28,"karbonhidrat":40,"yag":20,"hazirlamaSuresi":15,"zorluk":"kolay"},
  66,
      "yag": 8,
      {"id":"EKO_OGLE_013","ad":"Kuzu "hazirlamaSuresi": 30,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_AKSAM_029",
      "ad": Kıymalı Patlıcan "Haşlama Tavuk + Musakka + Yoğurt","ogun":"ogle","malzemeler":["Kuzu Sebzeli Bulgur Pilavı",
      "ogun": "aksam",
      "malzemeler": Kıyma ["Tavuk Göğüs 140g", "Bulgur 90g","Patlıcan 150g","Domates 60g","Yoğurt 60g", "Havuç 50g", "Bezelye 40g"],
      "kalori": 450,
      "protein": 43,
      "karbonhidrat": 80g"],"kalori":445,"protein":28,"karbonhidrat":32,"yag":22,"hazirlamaSuresi":50,"zorluk":"orta"},
  50,
      "yag": 9,
      {"id":"EKO_OGLE_014","ad":"Haşlanmış Tavuk Göğüs + "hazirlamaSuresi": 35,
      "zorluk": "kolay"
    },
    Kinoa {
      "id": "EKO_AKSAM_030",
      "ad": "Kuzu Salatası","ogun":"ogle","malzemeler":["Tavuk Göğüs 140g","Kinoa 50g","Marul Kıymalı Nohut + Bulgur Pilavı",
      "ogun": "aksam",
      "malzemeler": ["Kuzu 80g","Domates Kıyma 80g", "Nohut 105g", "Bulgur 50g"],
      60g"],"kalori":440,"protein":42,"karbonhidrat":38,"yag":12,"hazirlamaSuresi":25,"zorluk":"kolay"},
  "kalori": 490,
      "protein": 31,
      "karbonhidrat": 60,
      "yag": {"id":"EKO_OGLE_015","ad":"Hamsi Tava + 16,
      "hazirlamaSuresi": 50,
      "zorluk": Mısır Ekmeği + "orta"
    },
    {
      "id": "EKO_AKSAM_031",
      "ad": Salata","ogun":"ogle","malzemeler":["Hamsi "Yumurtalı Sebze Sote + Bulgur Pilavı",
      "ogun": "aksam",
      "malzemeler": ["Yumurta 100g", 150g","Mısır Unu 40g","Marul 100g","Limon "Biber 80g", "Domates 80g", "Bulgur 50g"],
      "kalori": 430,
      "protein": 25,
      "karbonhidrat": 52,
      "yag": 14,
      "hazirlamaSuresi": 20,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_AKSAM_032",
      "ad": 20g"],"kalori":475,"protein":38,"karbonhidrat":35,"yag":20,"hazirlamaSuresi":20,"zorluk":"kolay"},
  {"id":"EKO_OGLE_016","ad":"Mercimekli Bulgur Pilavı + Yoğurt","ogun":"ogle","malzemeler":["Kırmızı "Tavuk Sote + Sebzeli Esmer Pirinç",
      Mercimek 60g","Bulgur 50g","Yoğurt "ogun": "aksam",
      "malzemeler": ["Tavuk Göğüs 140g", "Esmer Pirinç 50g", "Biber 60g", "Havuç 50g"],
      "kalori": 460,
      "protein": 44,
      "karbonhidrat": 50,
      "yag": 10,
      100g"],"kalori":430,"protein":20,"karbonhidrat":65,"yag":9,"hazirlamaSuresi":30,"zorluk":"kolay"},
  {"id":"EKO_OGLE_017","ad":"Tavuk Sote + Esmer Pirinç + "hazirlamaSuresi": 30,
      "zorluk": "kolay"
    },
    {
      "id": Salata","ogun":"ogle","malzemeler":["Tavuk Göğüs 140g","Esmer "EKO_AKSAM_033",
      "ad": "Barbunya + Sebzeli Pirinç 50g","Biber Bulgur Pilavı + Turşu",
      "ogun": "aksam",
      60g","Domates "malzemeler": ["Barbunya 130g", "Bulgur 50g", "Havuç 50g", "Turşu 30g"],
      "kalori": 435,
      "protein": 60g"],"kalori":455,"protein":43,"karbonhidrat":45,"yag":10,"hazirlamaSuresi":30,"zorluk":"kolay"},
  20,
      "karbonhidrat": 70,
      "yag": 9,
      {"id":"EKO_OGLE_018","ad":"Dana Kıymalı Kuru "hazirlamaSuresi": 45,
      "zorluk": "orta"
    },
    Fasulye + {
      "id": "EKO_AKSAM_034",
      "ad": "Hamsi Bulgur","ogun":"ogle","malzemeler":["Dana Kıyma 80g","Kuru Fasulye 100g","Bulgur Buğulama + Bulgur Pilavı + Salata",
      "ogun": 50g","Soğan "aksam",
      "malzemeler": ["Hamsi 150g", "Bulgur 60g", "Marul 80g", "Limon 20g"],
      30g"],"kalori":490,"protein":32,"karbonhidrat":60,"yag":14,"hazirlamaSuresi":50,"zorluk":"orta"},
  "kalori": 465,
      "protein": 39,
      {"id":"EKO_OGLE_019","ad":"Izgara "karbonhidrat": 50,
      "yag": 12,
      "hazirlamaSuresi": 25,
      Sardalya + Bulgur "zorluk": "kolay"
    },
    {
      "id": Pilavı","ogun":"ogle","malzemeler":["Sardalya 140g","Bulgur 60g","Marul "EKO_AKSAM_035",
      "ad": "Dana Kıymalı Mercimek + 100g","Limon Yoğurt + Pilav",
      "ogun": "aksam",
      "malzemeler": ["Dana Kıyma 80g", "Yeşil Mercimek 85g", 20g"],"kalori":465,"protein":36,"karbonhidrat":42,"yag":16,"hazirlamaSuresi":20,"zorluk":"kolay"},
  "Yoğurt 100g", "Bulgur 45g"],
      {"id":"EKO_OGLE_020","ad":"Sebzeli Tavuk Güveç "kalori": 485,
      "protein": 35,
      + Bulgur "karbonhidrat": 58,
      "yag": 14,
      "hazirlamaSuresi": 40,
      Pilavı","ogun":"ogle","malzemeler":["Tavuk But 130g","Patlıcan "zorluk": "orta"
    },
    {
      "id": 80g","Domates 70g","Bulgur "EKO_AKSAM_036",
      "ad": "Fırında Tavuk Kanat + Sebze Garnitür",
      "ogun": "aksam",
      "malzemeler": 50g"],"kalori":450,"protein":35,"karbonhidrat":48,"yag":14,"hazirlamaSuresi":45,"zorluk":"orta"},
  ["Tavuk Kanat 175g", {"id":"EKO_OGLE_021","ad":"Nohutlu Bulgur Pilavı + "Patates 100g", "Havuç 60g"],
      "kalori": 490,
      "protein": 41,
      Cacık","ogun":"ogle","malzemeler":["Nohut 100g","Bulgur "karbonhidrat": 40,
      "yag": 20,
      60g","Yoğurt 100g","Salatalık "hazirlamaSuresi": 45,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_AKSAM_037",
      "ad": 50g"],"kalori":445,"protein":20,"karbonhidrat":68,"yag":10,"hazirlamaSuresi":35,"zorluk":"kolay"},
  "Nohutlu Bulgur Pilavı + {"id":"EKO_OGLE_022","ad":"Haşlama Tavuk Cacık",
      "ogun": "aksam",
      "malzemeler": ["Nohut 105g", "Bulgur + Sebze 60g", "Yoğurt 100g", "Salatalık 50g"],
      Püresi","ogun":"ogle","malzemeler":["Tavuk Göğüs "kalori": 450,
      "protein": 21,
      "karbonhidrat": 70,
      "yag": 150g","Patates 100g","Havuç 10,
      "hazirlamaSuresi": 35,
      "zorluk": "kolay"
    },
    {
      60g","Kabak "id": "EKO_AKSAM_038",
      "ad": "Kuzu Kıymalı Patlıcan Kızartma + 60g"],"kalori":440,"protein":44,"karbonhidrat":38,"yag":12,"hazirlamaSuresi":40,"zorluk":"kolay"},
  Yoğurt",
      "ogun": "aksam",
      "malzemeler": ["Kuzu Kıyma 90g", {"id":"EKO_OGLE_023","ad":"Yumurtalı Ispanak + Yoğurt "Patlıcan 130g", + "Yoğurt 80g", "Bulgur 45g"],
      "kalori": 480,
      "protein": Bulgur","ogun":"ogle","malzemeler":["Yumurta 100g","Ispanak 150g","Yoğurt 31,
      "karbonhidrat": 50,
      "yag": 80g","Bulgur 20,
      "hazirlamaSuresi": 45,
      "zorluk": "orta"
    },
    {
      "id": 50g"],"kalori":435,"protein":26,"karbonhidrat":48,"yag":16,"hazirlamaSuresi":25,"zorluk":"kolay"},
  "EKO_AKSAM_039",
      "ad": "Izgara Tavuk Göğüs + Kinoa {"id":"EKO_OGLE_024","ad":"Kuzu + Salata",
      "ogun": "aksam",
      "malzemeler": ["Tavuk Göğüs Kıymalı Türlü + 150g", "Kinoa 50g", "Marul Yoğurt","ogun":"ogle","malzemeler":["Kuzu Kıyma 100g"],
      "kalori": 450,
      "protein": 46,
      90g","Patlıcan 80g","Kabak 70g","Yoğurt "karbonhidrat": 40,
      "yag": 12,
      "hazirlamaSuresi": 25,
      "zorluk": "kolay"
    },
    {
      "id": 100g"],"kalori":455,"protein":28,"karbonhidrat":36,"yag":22,"hazirlamaSuresi":45,"zorluk":"orta"},
  "EKO_AKSAM_040",
      "ad": "Mercimek Çorbası + Peynirli Sandviç",
      "ogun": "aksam",
      "malzemeler": ["Kırmızı Mercimek 60g", "Tam Buğday Ekmeği 80g", "Beyaz Peynir 70g"],
      "kalori": {"id":"EKO_OGLE_025","ad":"Tavuklu Nohut Yemeği + Bulgur Pilavı","ogun":"ogle","malzemeler":["Tavuk But 100g","Nohut 100g","Bulgur 50g","Soğan 465,
      "protein": 28,
      "karbonhidrat": 58,
      "yag": 14,
      "hazirlamaSuresi": 25,
      30g"],"kalori":480,"protein":32,"karbonhidrat":60,"yag":14,"hazirlamaSuresi":45,"zorluk":"orta"},
  "zorluk": "kolay"
    },
    {
      "id": {"id":"EKO_OGLE_026","ad":"Uskumru Tava + "EKO_AKSAM_041",
      "ad": Patates "Tavuk Güveç + Esmer Pirinç + Pilav",
      Kızartması","ogun":"ogle","malzemeler":["Uskumru 140g","Patates 120g","Marul "ogun": "aksam",
      "malzemeler": ["Tavuk But 140g", "Patlıcan 80g", "Esmer Pirinç 50g"],
      "kalori": 470,
      "protein": 39,
      "karbonhidrat": 80g"],"kalori":510,"protein":35,"karbonhidrat":40,"yag":24,"hazirlamaSuresi":25,"zorluk":"kolay"},
  50,
      "yag": 14,
      "hazirlamaSuresi": {"id":"EKO_OGLE_027","ad":"Dana Kıymalı Ispanak + Yoğurt 55,
      "zorluk": "orta"
    },
    {
      "id": + Pilav","ogun":"ogle","malzemeler":["Dana Kıyma "EKO_AKSAM_042",
      "ad": 90g","Ispanak 150g","Yoğurt 100g","Esmer Pirinç "Yumurtalı Ispanak + Yoğurt + Bulgur",
      "ogun": "aksam",
      "malzemeler": ["Yumurta 100g", "Ispanak 150g", 50g"],"kalori":470,"protein":32,"karbonhidrat":45,"yag":18,"hazirlamaSuresi":35,"zorluk":"kolay"},
  "Yoğurt 80g", "Bulgur 50g"],
      {"id":"EKO_OGLE_028","ad":"Tavuk "kalori": 440,
      "protein": 27,
      "karbonhidrat": 50,
      Haşlama + Sebzeli "yag": 16,
      "hazirlamaSuresi": Bulgur Pilavı","ogun":"ogle","malzemeler":["Tavuk 25,
      "zorluk": "kolay"
    },
    {
      "id": Göğüs 140g","Bulgur "EKO_AKSAM_043",
      "ad": "Kuru Fasulye 60g","Havuç 50g","Bezelye + Sebzeli Bulgur Pilavı",
      "ogun": "aksam",
      "malzemeler": ["Kuru Fasulye 120g", "Bulgur 50g", 40g"],"kalori":445,"protein":42,"karbonhidrat":48,"yag":9,"hazirlamaSuresi":30,"zorluk":"kolay"},
  "Havuç 50g"],
      "kalori": 445,
      "protein": 21,
      {"id":"EKO_OGLE_029","ad":"Mercimekli "karbonhidrat": 72,
      "yag": 8,
      "hazirlamaSuresi": Köfte + Salata + 55,
      "zorluk": "orta"
    },
    {
      "id": Yoğurt","ogun":"ogle","malzemeler":["Kırmızı Mercimek 80g","Bulgur "EKO_AKSAM_044",
      "ad": 50g","Marul 100g","Yoğurt "Izgara Sardalya + Esmer Pirinç + Salata",
      "ogun": "aksam",
      "malzemeler": ["Sardalya 145g", "Esmer Pirinç 50g", 100g"],"kalori":425,"protein":22,"karbonhidrat":64,"yag":8,"hazirlamaSuresi":30,"zorluk":"kolay"},
  "Marul 100g"],
      "kalori": 475,
      "protein": {"id":"EKO_OGLE_030","ad":"Fırında Tavuk 38,
      "karbonhidrat": 45,
      "yag": 16,
      Kanat + Sebze "hazirlamaSuresi": 20,
      "zorluk": "kolay"
    Garnitür","ogun":"ogle","malzemeler":["Tavuk Kanat 170g","Patates 100g","Havuç 60g","Soğan },
    {
      "id": "EKO_AKSAM_045",
      "ad": "Dana Kıymalı Sebze Sote + Bulgur Pilavı",
      "ogun": "aksam",
      "malzemeler": ["Dana Kıyma 40g"],"kalori":485,"protein":40,"karbonhidrat":38,"yag":20,"hazirlamaSuresi":40,"zorluk":"kolay"},
  100g", "Biber 70g", {"id":"EKO_OGLE_031","ad":"Kuru Fasulye + "Domates 70g", "Bulgur 50g"],
      "kalori": 480,
      "protein": 35,
      "karbonhidrat": 50,
      "yag": Esmer Pirinç Pilavı","ogun":"ogle","malzemeler":["Kuru Fasulye 120g","Esmer 16,
      Pirinç 50g","Soğan "hazirlamaSuresi": 25,
      "zorluk": "kolay"
    },
    {
      "id": "EKO_AKSAM_046",
      "ad": "Haşlama Tavuk Göğüs + Patates Püresi",
      "ogun": "aksam",
      "malzemeler": ["Tavuk Göğüs 30g"],"kalori":450,"protein":20,"karbonhidrat":72,"yag":8,"hazirlamaSuresi":50,"zorluk":"orta"},
  {"id":"EKO_OGLE_032","ad":"Haşlanmış Yumurta (3) + Tam 145g", "Patates 130g", Buğday Ekmeği","ogun":"ogle","malzemeler":["Yumurta 150g","Tam Buğday Ekmeği 80g","Marul 100g","Domates "Süt 30ml"],
      "kalori": 455,
      "protein": 43,
      "karbonhidrat": 48,
      "yag": 10,
      "hazirlamaSuresi": 35,
      60g"],"kalori":440,"protein":28,"karbonhidrat":48,"yag":16,"hazirlamaSuresi":15,"zorluk":"kolay"},
  "zorluk": "kolay"
    },
    {
      "id": "EKO_AKSAM_047",
      "ad": {"id":"EKO_OGLE_033","ad":"Tavuklu Sebze "Uskumru Sote + Bulgur Izgara + Bulgur Pilavı + Salata",
      "ogun": "aksam",
      Pilavı","ogun":"ogle","malzemeler":["Tavuk Göğüs 130g","Biber "malzemeler": ["Uskumru 140g", "Bulgur 60g", 70g","Domates 70g","Bulgur "Marul 80g"],
      "kalori": 510,
      "protein": 36,
      "karbonhidrat": 48,
      "yag": 50g"],"kalori":435,"protein":40,"karbonhidrat":46,"yag":10,"hazirlamaSuresi":25,"zorluk":"kolay"},
  22,
      "hazirlamaSuresi": 20,
      {"id":"EKO_OGLE_034","ad":"Nohutlu Ispanak + Yoğurt","ogun":"ogle","malzemeler":["Nohut "zorluk": "kolay"
    },
    {
      "id": 100g","Ispanak 150g","Yoğurt "EKO_AKSAM_048",
      "ad": "Nohutlu Ispanak + Yoğurt",
      "ogun": "aksam",
      "malzemeler": ["Nohut 105g", "Ispanak 150g", "Yoğurt 120g"],
      120g"],"kalori":420,"protein":22,"karbonhidrat":52,"yag":14,"hazirlamaSuresi":30,"zorluk":"kolay"},
  {"id":"EKO_OGLE_035","ad":"Dana Kıymalı "kalori": 425,
      "protein": 24,
      "karbonhidrat": Kabak Dolması + 54,
      "yag": 13,
      "hazirlamaSuresi": 30,
      Yoğurt","ogun":"ogle","malzemeler":["Dana Kıyma 90g","Kabak "zorluk": "kolay"
    },
    {
      "id": 150g","Pirinç 30g","Yoğurt "EKO_AKSAM_049",
      "ad": "Omlet (2 Yumurta) + 100g"],"kalori":445,"protein":30,"karbonhidrat":42,"yag":18,"hazirlamaSuresi":45,"zorluk":"orta"},
  Peynir + Ekmek + Salata",
      "ogun": "aksam",
      "malzemeler": ["Yumurta 100g", "Beyaz Peynir 60g", "Tam Buğday Ekmeği 80g", "Domates 50g"],
      "kalori": 465,
      "protein": {"id":"EKO_OGLE_036","ad":"Hamsi Buğulama 31,
      "karbonhidrat": 44,
      "yag": + Bulgur Pilavı","ogun":"ogle","malzemeler":["Hamsi 150g","Bulgur 60g","Marul 80g","Limon 20,
      "hazirlamaSuresi": 15,
      "zorluk": 20g"],"kalori":460,"protein":38,"karbonhidrat":48,"yag":12,"hazirlamaSuresi":25,"zorluk":"kolay"},
  "kolay"
    },
    {
      "id": "EKO_AKSAM_050",
      {"id":"EKO_OGLE_037","ad":"Barbunya "ad": "Barbunya Pilaki + Bulgur Pilavı + + Sebzeli Bulgur Yoğurt",
      "ogun": "aksam",
      "malzemeler": ["Barbunya Pilavı","ogun":"ogle","malzemeler":["Barbunya 130g","Bulgur 130g", "Bulgur 50g", "Yoğurt 100g"],
      "kalori": 50g","Havuç 50g","Soğan 445,
      "protein": 21,
      "karbonhidrat": 68,
      "yag": 10,
      "hazirlamaSuresi": 40g"],"kalori":430,"protein":19,"karbonhidrat":68,"yag":9,"hazirlamaSuresi":40,"zorluk":"orta"},
  45,
      "zorluk": "orta"
    },
  ];
}
