name: zinde_ai
description: Yapay zeka destekli fitness ve beslenme uygulaması
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  provider: ^6.1.1
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # Network
  dio: ^5.3.3
  connectivity_plus: ^5.0.1
  
  # UI
  fl_chart: ^0.65.0
  table_calendar: ^3.0.9
  shimmer: ^3.0.0
  
  # Utils
  intl: ^0.18.1
  logger: ^2.0.2
  dartz: ^0.10.1
  
  # Video
  video_player: ^2.8.1
  chewie: ^1.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  mockito: ^5.4.3
  bloc_test: ^9.1.5
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/
    - assets/images/
