// MEGA YEMEK BATCH 20 - SAĞLIKLI KAHVALTI (500+ Eklenti - 1/12)
// Diyetisyen Onaylı, Kolay Bulunabilir, Türk Mutfağı

List<Map<String, dynamic>> getMegaYemekBatch20() {
  return [
    {'id': 'K951', 'kategori': 'kahvalti', 'ad': 'Haşlanmış Yumurta + Tam Buğday Ekmeği', 'kalori': 285.0, 'protein': 18.0, 'karbonhidrat': 32.0, 'yag': 9.0, 'hazirlamaSuresi': 15, 'zorluk': 'Kolay', 'malzemeler': ['Haşlanmış yumurta 2 adet', 'Tam buğday ekmeği 2 dilim', 'Domates 1 adet', 'Salatalık']},
    {'id': 'K952', 'kategori': 'kahvalti', 'ad': 'Lor Peyniri + Ceviz + Bal', 'kalori': 310.0, 'protein': 16.0, 'karbonhidrat': 38.0, 'yag': 11.0, 'hazirlamaSuresi': 5, 'zorluk': 'Kolay', 'malzemeler': ['Lor peyniri 100g', 'Ceviz 30g', 'Bal 1 çorba kaşığı', 'Kepekli ekmek 2 dilim']},
    {'id': 'K953', 'kategori': 'kahvalti', 'ad': 'Sade Yulaf + Süt + Muz', 'kalori': 295.0, 'protein': 12.0, 'karbonhidrat': 52.0, 'yag': 5.0, 'hazirlamaSuresi': 10, 'zorluk': 'Kolay', 'malzemeler': ['Yulaf 60g', 'Süt 200ml', 'Muz 1 adet', 'Tarçın']},
    {'id': 'K954', 'kategori': 'kahvalti', 'ad': 'Zeytinli Yumurta + Domates', 'kalori': 305.0, 'protein': 20.0, 'karbonhidrat': 18.0, 'yag': 16.0, 'hazirlamaSuresi': 12, 'zorluk': 'Kolay', 'malzemeler': ['Yumurta 3 adet', 'Siyah zeytin 50g', 'Domates 2 adet', 'Kepekli ekmek 1 dilim']},
    {'id': 'K955', 'kategori': 'kahvalti', 'ad': 'Süzme Yoğurt + Hurma + Badem', 'kalori': 320.0, 'protein': 18.0, 'karbonhidrat': 42.0, 'yag': 9.0, 'hazirlamaSuresi': 5, 'zorluk': 'Kolay', 'malzemeler': ['Süzme yoğurt 200g', 'Hurma 3 adet', 'Badem 20g']},
    
    {'id': 'K956', 'kategori': 'kahvalti', 'ad': 'Peynirli Ispanak Omlet', 'kalori': 295.0, 'protein': 24.0, 'karbonhidrat': 12.0, 'yag': 16.0, 'hazirlamaSuresi': 15, 'zorluk': 'Kolay', 'malzemeler': ['Yumurta 3 adet', 'Ispanak 100g', 'Beyaz peynir 50g', 'Soğan']},
    {'id': 'K957', 'kategori': 'kahvalti', 'ad': 'Tahin + Pekmez + Ekmek', 'kalori': 340.0, 'protein': 10.0, 'karbonhidrat': 48.0, 'yag': 13.0, 'hazirlamaSuresi': 5, 'zorluk': 'Kolay', 'malzemeler': ['Tahin 20g', 'Pekmez 30g', 'Tam buğday ekmeği 2 dilim']},
    {'id': 'K958', 'kategori': 'kahvalti', 'ad': 'Kırmızı Mercimek Çorbası + Ekmek', 'kalori': 280.0, 'protein': 14.0, 'karbonhidrat': 48.0, 'yag': 4.0, 'hazirlamaSuresi': 25, 'zorluk': 'Orta', 'malzemeler': ['Kırmızı mercimek 80g', 'Ekmek 1 dilim', 'Limon', 'Soğan', 'Zeytinyağı']},
    {'id': 'K959', 'kategori': 'kahvalti', 'ad': 'Çökelek + Domates + Salatalık', 'kalori': 260.0, 'protein': 22.0, 'karbonhidrat': 26.0, 'yag': 6.0, 'hazirlamaSuresi': 5, 'zorluk': 'Kolay', 'malzemeler': ['Çökelek 150g', 'Domates 2 adet', 'Salatalık 1 adet', 'Kepekli ekmek 2 dilim']},
    {'id': 'K960', 'kategori': 'kahvalti', 'ad': 'Ev Yapımı Yumurtalı Ekmek', 'kalori': 315.0, 'protein': 16.0, 'karbonhidrat': 38.0, 'yag': 11.0, 'hazirlamaSuresi': 10, 'zorluk': 'Kolay', 'malzemeler': ['Ekmek 2 dilim', 'Yumurta 2 adet', 'Süt 50ml', 'Zeytinyağı']},

    {'id': 'K961', 'kategori': 'kahvalti', 'ad': 'Menemen + Ekmek', 'kalori': 305.0, 'protein': 18.0, 'karbonhidrat': 28.0, 'yag': 13.0, 'hazirlamaSuresi': 15, 'zorluk': 'Kolay', 'malzemeler': ['Yumurta 3 adet', 'Domates 2 adet', 'Biber 1 adet', 'Soğan', 'Ekmek 1 dilim']},
    {'id': 'K962', 'kategori': 'kahvalti', 'ad': 'Yoğurt + Ceviz + Bal', 'kalori': 290.0, 'protein': 14.0, 'karbonhidrat': 38.0, 'yag': 10.0, 'hazirlamaSuresi': 5, 'zorluk': 'Kolay', 'malzemeler': ['Yoğurt 200g', 'Ceviz 25g', 'Bal 15g']},
    {'id': 'K963', 'kategori': 'kahvalti', 'ad': 'Peynirli Domates Salata', 'kalori': 275.0, 'protein': 16.0, 'karbonhidrat': 24.0, 'yag': 12.0, 'hazirlamaSuresi': 8, 'zorluk': 'Kolay', 'malzemeler': ['Beyaz peynir 100g', 'Domates 2 adet', 'Salatalık 1 adet', 'Zeytinyağı', 'Ekmek 1 dilim']},
    {'id': 'K964', 'kategori': 'kahvalti', 'ad': 'Tereyağlı Yumurta + Ekmek', 'kalori': 320.0, 'protein': 18.0, 'karbonhidrat': 30.0, 'yag': 14.0, 'hazirlamaSuresi': 10, 'zorluk': 'Kolay', 'malzemeler': ['Yumurta 3 adet', 'Tereyağı 10g', 'Tam buğday ekmeği 2 dilim']},
    {'id': 'K965', 'kategori': 'kahvalti', 'ad': 'Kefir + Ceviz + Hurma', 'kalori': 285.0, 'protein': 12.0, 'karbonhidrat': 44.0, 'yag': 8.0, 'hazirlamaSuresi': 5, 'zorluk': 'Kolay', 'malzemeler': ['Kefir 250ml', 'Ceviz 20g', 'Hurma 3 adet']},

    {'id': 'K966', 'kategori': 'kahvalti', 'ad': 'Haşlanmış Yumurta + Avokado', 'kalori': 330.0, 'protein': 16.0, 'karbonhidrat': 22.0, 'yag': 19.0, 'hazirlamaSuresi': 12, 'zorluk': 'Kolay', 'malzemeler': ['Haşlanmış yumurta 2 adet', 'Avokado yarım', 'Kepekli ekmek 2 dilim', 'Limon']},
    {'id': 'K967', 'kategori': 'kahvalti', 'ad': 'Beyaz Peynir + Zeytin + Domates', 'kalori': 270.0, 'protein': 18.0, 'karbonhidrat': 26.0, 'yag': 10.0, 'hazirlamaSuresi': 5, 'zorluk': 'Kolay', 'malzemeler': ['Beyaz peynir 80g', 'Zeytin 50g', 'Domates 2 adet', 'Ekmek 2 dilim']},
    {'id': 'K968', 'kategori': 'kahvalti', 'ad': 'Yumurtalı Sucuklu Omlet', 'kalori': 380.0, 'protein': 26.0, 'karbonhidrat': 18.0, 'yag': 22.0, 'hazirlamaSuresi': 12, 'zorluk': 'Kolay', 'malzemeler': ['Yumurta 3 adet', 'Sucuk 50g', 'Domates', 'Ekmek 1 dilim']},
    {'id': 'K969', 'kategori': 'kahvalti', 'ad': 'Ezogelin Çorbası + Ekmek', 'kalori': 295.0, 'protein': 12.0, 'karbonhidrat': 50.0, 'yag': 5.0, 'hazirlamaSuresi': 30, 'zorluk': 'Orta', 'malzemeler': ['Kırmızı mercimek 60g', 'Bulgur 40g', 'Ekmek 1 dilim', 'Domates salçası', 'Soğan']},
    {'id': 'K970', 'kategori': 'kahvalti', 'ad': 'Labne + Ceviz + Bal', 'kalori': 305.0, 'protein': 16.0, 'karbonhidrat': 36.0, 'yag': 11.0, 'hazirlamaSuresi': 5, 'zorluk': 'Kolay', 'malzemeler': ['Labne 120g', 'Ceviz 25g', 'Bal 15g', 'Kepekli ekmek 1 dilim']},

    {'id': 'K971', 'kategori': 'kahvalti', 'ad': 'Patlıcanlı Yumurta', 'kalori': 290.0, 'protein': 16.0, 'karbonhidrat': 24.0, 'yag': 14.0, 'hazirlamaSuresi': 18, 'zorluk': 'Orta', 'malzemeler': ['Yumurta 2 adet', 'Patlıcan 1 adet', 'Domates', 'Zeytinyağı', 'Ekmek']},
    {'id': 'K972', 'kategori': 'kahvalti', 'ad': 'Beyaz Peynir + Domates + Salatalık', 'kalori': 255.0, 'protein': 20.0, 'karbonhidrat': 22.0, 'yag': 8.0, 'hazirlamaSuresi': 5, 'zorluk': 'Kolay', 'malzemeler': ['Beyaz peynir 100g', 'Domates 2 adet', 'Salatalık 1 adet', 'Ekmek 1 dilim']},
    {'id': 'K973', 'kategori': 'kahvalti', 'ad': 'Yulaf + Yoğurt + Meyve', 'kalori': 310.0, 'protein': 14.0, 'karbonhidrat': 50.0, 'yag': 6.0, 'hazirlamaSuresi': 8, 'zorluk': 'Kolay', 'malzemeler': ['Yulaf 50g', 'Yoğurt 150g', 'Elma 1 adet', 'Tarçın']},
    {'id': 'K974', 'kategori': 'kahvalti', 'ad': 'Kaşarlı Omlet', 'kalori': 325.0, 'protein': 24.0, 'karbonhidrat': 14.0, 'yag': 18.0, 'hazirlamaSuresi': 10, 'zorluk': 'Kolay', 'malzemeler': ['Yumurta 3 adet', 'Kaşar peyniri 50g', 'Domates', 'Ekmek 1 dilim']},
    {'id': 'K975', 'kategori': 'kahvalti', 'ad': 'Haşlanmış Yumurta + Taze Fasulye Salatası', 'kalori': 275.0, 'protein': 18.0, 'karbonhidrat': 32.0, 'yag': 8.0, 'hazirlamaSuresi': 25, 'zorluk': 'Orta', 'malzemeler': ['Haşlanmış yumurta 2 adet', 'Taze fasulye 150g', 'Zeytinyağı', 'Limon', 'Ekmek']},

    {'id': 'K976', 'kategori': 'kahvalti', 'ad': 'Lor Peyniri + Domates + Salatalık', 'kalori': 245.0, 'protein': 20.0, 'karbonhidrat': 24.0, 'yag': 6.0, 'hazirlamaSuresi': 5, 'zorluk': 'Kolay', 'malzemeler': ['Lor peyniri 120g', 'Domates 2 adet', 'Salatalık 1 adet', 'Kepekli ekmek 2 dilim']},
    {'id': 'K977', 'kategori': 'kahvalti', 'ad': 'Yumurtalı Ispanak', 'kalori': 280.0, 'protein': 22.0, 'karbonhidrat': 16.0, 'yag': 13.0, 'hazirlamaSuresi': 15, 'zorluk': 'Kolay', 'malzemeler': ['Yumurta 3 adet', 'Ispanak 150g', 'Soğan', 'Zeytinyağı']},
    {'id': 'K978', 'kategori': 'kahvalti', 'ad': 'Süzme Yoğurt + Bal + Fındık', 'kalori': 315.0, 'protein': 18.0, 'karbonhidrat': 38.0, 'yag': 10.0, 'hazirlamaSuresi': 5, 'zorluk': 'Kolay', 'malzemeler': ['Süzme yoğurt 200g', 'Bal 20g', 'Fındık 25g']},
    {'id': 'K979', 'kategori': 'kahvalti', 'ad': 'Peynirli Pırasa Böreği', 'kalori': 340.0, 'protein': 16.0, 'karbonhidrat': 42.0, 'yag': 12.0, 'hazirlamaSuresi': 35, 'zorluk': 'Orta', 'malzemeler': ['Yufka 2 adet', 'Pırasa 150g', 'Beyaz peynir 60g', 'Yumurta', 'Zeytinyağı']},
    {'id': 'K980', 'kategori': 'kahvalti', 'ad': 'Kırmızı Mercimek Köftesi', 'kalori': 295.0, 'protein': 12.0, 'karbonhidrat': 52.0, 'yag': 4.0, 'hazirlamaSuresi': 30, 'zorluk': 'Orta', 'malzemeler': ['Kırmızı mercimek 100g', 'Bulgur 60g', 'Soğan', 'Maydanoz', 'Limon']},

    {'id': 'K981', 'kategori': 'kahvalti', 'ad': 'Haşlanmış Yumurta + Lor Peyniri', 'kalori': 270.0, 'protein': 26.0, 'karbonhidrat': 18.0, 'yag': 9.0, 'hazirlamaSuresi': 12, 'zorluk': 'Kolay', 'malzemeler': ['Haşlanmış yumurta 2 adet', 'Lor peyniri 100g', 'Ekmek 1 dilim', 'Domates']},
    {'id': 'K982', 'kategori': 'kahvalti', 'ad': 'Yoğurt + Elma + Ceviz', 'kalori': 285.0, 'protein': 12.0, 'karbonhidrat': 42.0, 'yag': 8.0, 'hazirlamaSuresi': 5, 'zorluk': 'Kolay', 'malzemeler': ['Yoğurt 200g', 'Elma 1 adet', 'Ceviz 20g', 'Tarçın']},
    {'id': 'K983', 'kategori': 'kahvalti', 'ad': 'Sebzeli Omlet', 'kalori': 290.0, 'protein': 20.0, 'karbonhidrat': 18.0, 'yag': 14.0, 'hazirlamaSuresi': 15, 'zorluk': 'Kolay', 'malzemeler': ['Yumurta 3 adet', 'Domates', 'Biber', 'Mantar', 'Soğan', 'Ekmek']},
    {'id': 'K984', 'kategori': 'kahvalti', 'ad': 'Beyaz Peynir + Zeytin + Salatalık', 'kalori': 260.0, 'protein': 18.0, 'karbonhidrat': 24.0, 'yag': 9.0, 'hazirlamaSuresi': 5, 'zorluk': 'Kolay', 'malzemeler': ['Beyaz peynir 90g', 'Siyah zeytin 40g', 'Salatalık 1 adet', 'Ekmek 2 dilim']},
    {'id': 'K985', 'kategori': 'kahvalti', 'ad': 'Tereyağlı Haşlanmış Yumurta', 'kalori': 305.0, 'protein': 16.0, 'karbonhidrat': 28.0, 'yag': 13.0, 'hazirlamaSuresi': 12, 'zorluk': 'Kolay', 'malzemeler': ['Haşlanmış yumurta 2 adet', 'Tereyağı 15g', 'Ekmek 2 dilim', 'Domates']},

    {'id': 'K986', 'kategori': 'kahvalti', 'ad': 'Kefir + Badem + Hurma', 'kalori': 295.0, 'protein': 14.0, 'karbonhidrat': 46.0, 'yag': 7.0, 'hazirlamaSuresi': 5, 'zorluk': 'Kolay', 'malzemeler': ['Kefir 250ml', 'Badem 20g', 'Hurma 3 adet']},
    {'id': 'K987', 'kategori': 'kahvalti', 'ad': 'Peynirli Domates Biber Salata', 'kalori': 285.0, 'protein': 16.0, 'karbonhidrat': 26.0, 'yag': 11.0, 'hazirlamaSuresi': 8, 'zorluk': 'Kolay', 'malzemeler': ['Beyaz peynir 80g', 'Domates 2 adet', 'Yeşil biber 1 adet', 'Zeytinyağı', 'Ekmek']},
    {'id': 'K988', 'kategori': 'kahvalti', 'ad': 'Yulaf + Süt + Elma', 'kalori': 300.0, 'protein': 12.0, 'karbonhidrat': 54.0, 'yag': 5.0, 'hazirlamaSuresi': 10, 'zorluk': 'Kolay', 'malzemeler': ['Yulaf 60g', 'Süt 200ml', 'Elma 1 adet', 'Tarçın']},
    {'id': 'K989', 'kategori': 'kahvalti', 'ad': 'Kavurmalı Yumurta', 'kalori': 360.0, 'protein': 24.0, 'karbonhidrat': 16.0, 'yag': 22.0, 'hazirlamaSuresi': 15, 'zorluk': 'Kolay', 'malzemeler': ['Yumurta 2 adet', 'Kavurma 60g', 'Domates', 'Biber', 'Ekmek']},
    {'id': 'K990', 'kategori': 'kahvalti', 'ad': 'Lor Peyniri + Bal + Ceviz', 'kalori': 320.0, 'protein': 18.0, 'karbonhidrat': 40.0, 'yag': 10.0, 'hazirlamaSuresi': 5, 'zorluk': 'Kolay', 'malzemeler': ['Lor peyniri 120g', 'Bal 20g', 'Ceviz 25g', 'Ekmek 1 dilim']},

    {'id': 'K991', 'kategori': 'kahvalti', 'ad': 'Haşlanmış Yumurta + Zeytinli Salata', 'kalori': 295.0, 'protein': 18.0, 'karbonhidrat': 24.0, 'yag': 12.0, 'hazirlamaSuresi': 15, 'zorluk': 'Kolay', 'malzemeler': ['Haşlanmış yumurta 2 adet', 'Siyah zeytin 50g', 'Salatalık', 'Domates', 'Ekmek']},
    {'id': 'K992', 'kategori': 'kahvalti', 'ad': 'Süzme Yoğurt + Meyve', 'kalori': 275.0, 'protein': 20.0, 'karbonhidrat': 42.0, 'yag': 4.0, 'hazirlamaSuresi': 5, 'zorluk': 'Kolay', 'malzemeler': ['Süzme yoğurt 200g', 'Çilek 100g', 'Muz yarım']},
    {'id': 'K993', 'kategori': 'kahvalti', 'ad': 'Peynirli Sucuklu Omlet', 'kalori': 385.0, 'protein': 28.0, 'karbonhidrat': 16.0, 'yag': 24.0, 'hazirlamaSuresi': 12, 'zorluk': 'Kolay', 'malzemeler': ['Yumurta 3 adet', 'Sucuk 40g', 'Kaşar peyniri 40g', 'Ekmek 1 dilim']},
    {'id': 'K994', 'kategori': 'kahvalti', 'ad': 'Yoğurtlu Havuç Salatası', 'kalori': 240.0, 'protein': 10.0, 'karbonhidrat': 34.0, 'yag': 7.0, 'hazirlamaSuresi': 10, 'zorluk': 'Kolay', 'malzemeler': ['Yoğurt 150g', 'Havuç rendelenmiş 150g', 'Sarımsak', 'Zeytinyağı', 'Ekmek']},
    {'id': 'K995', 'kategori': 'kahvalti', 'ad': 'Beyaz Peynir + Domates + Yeşil Biber', 'kalori': 270.0, 'protein': 19.0, 'karbonhidrat': 25.0, 'yag': 9.0, 'hazirlamaSuresi': 5, 'zorluk': 'Kolay', 'malzemeler': ['Beyaz peynir 90g', 'Domates 2 adet', 'Yeşil biber 1 adet', 'Ekmek 2 dilim']},

    {'id': 'K996', 'kategori': 'kahvalti', 'ad': 'Tahin + Pekmez + Kepekli Ekmek', 'kalori': 330.0, 'protein': 10.0, 'karbonhidrat': 46.0, 'yag': 12.0, 'hazirlamaSuresi': 5, 'zorluk': 'Kolay', 'malzemeler': ['Tahin 20g', 'Pekmez 25g', 'Kepekli ekmek 2 dilim']},
    {'id': 'K997', 'kategori': 'kahvalti', 'ad': 'Yumurtalı Patlıcan', 'kalori': 305.0, 'protein': 18.0, 'karbonhidrat': 22.0, 'yag': 15.0, 'hazirlamaSuresi': 20, 'zorluk': 'Orta', 'malzemeler': ['Yumurta 2 adet', 'Patlıcan 1 adet', 'Domates', 'Zeytinyağı', 'Ekmek']},
    {'id': 'K998', 'kategori': 'kahvalti', 'ad': 'Lor Peyniri + Domates + Maydanoz', 'kalori': 250.0, 'protein': 22.0, 'karbonhidrat': 22.0, 'yag': 6.0, 'hazirlamaSuresi': 5, 'zorluk': 'Kolay', 'malzemeler': ['Lor peyniri 120g', 'Domates 2 adet', 'Maydanoz', 'Ekmek 1 dilim']},
    {'id': 'K999', 'kategori': 'kahvalti', 'ad': 'Yulaf + Yoğurt + Ceviz', 'kalori': 315.0, 'protein': 14.0, 'karbonhidrat': 48.0, 'yag': 8.0, 'hazirlamaSuresi': 8, 'zorluk': 'Kolay', 'malzemeler': ['Yulaf 50g', 'Yoğurt 150g', 'Ceviz 20g', 'Bal 10g']},
    {'id': 'K1000', 'kategori': 'kahvalti', 'ad': 'Haşlanmış Yumurta + Çökelek', 'kalori': 285.0, 'protein': 28.0, 'karbonhidrat': 20.0, 'yag': 8.0, 'hazirlamaSuresi': 15, 'zorluk': 'Kolay', 'malzemeler': ['Haşlanmış yumurta 2 adet', 'Çökelek 100g', 'Domates', 'Ekmek 1 dilim']},
  ];
}
